"""Mirror the manuscript's figure legends into each gist README.

A gist is the reader-facing reproduction unit for one figure, and its
``01_<slug>.md`` is the first thing a reader sees. Until now those READMEs
carried hand-written prose that drifted from the manuscript — a reviewer
reading the paper and then clicking through to the gist could get two
different descriptions of the same panel, and in one case
(``evidence_corpus_vs_selected``) the README still described synthesized
placeholder data long after the figure plotted real records.

This script writes the manuscript legend verbatim into a marked block at
the top of every README, so the two cannot disagree. Everything outside
the markers — reproduction instructions, column docs, data lineage — is
left alone, because that is the gist's own job and is not in the paper.

Legends live in ``data/analysis/figures/manuscript_legends.json``, exported
from the Google Doc. The doc is not reachable from CI, so the export is
committed rather than fetched at run time.

Usage::

    uv run python scripts/figures/sync_readme_legends.py            # write
    uv run python scripts/figures/sync_readme_legends.py --check    # CI mode
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from accessible_surfaceome.paths import REPO_ROOT

FIG_DIR = REPO_ROOT / "data" / "analysis" / "figures"
LEGENDS_JSON = FIG_DIR / "manuscript_legends.json"

MARK_A = "<!-- BEGIN manuscript-legend (generated — edit the manuscript, not here) -->"
MARK_B = "<!-- END manuscript-legend -->"

# Counts the legends assert that we can check against the shipped data. A
# manuscript edit that lands a new cohort size should update these too;
# a mismatch is reported, never auto-corrected, because the manuscript is
# the authority on its own wording and only a human should restate a result.
_COHORT_TSV = REPO_ROOT / "data" / "processed" / "figures" / "deep_dive_final_categories.tsv"


def _figure_label(key: str) -> str:
    return key if key.startswith("Figure") else f"Supplementary Figure {key[1:]}"


def _clean(text: str) -> str:
    """Strip the Docs export's artifacts and the leading figure label.

    The label is re-added by the block template so every README renders it
    the same way regardless of how the doc happened to punctuate it.
    """
    text = re.sub(r"^\*\*", "", text)
    text = re.sub(r"^(Supplementary\s+)?Figure\s+S?\d+\.\s*", "", text)
    text = text.replace("**", "")
    # The gist links to its own data; the manuscript's trailing link is noise here.
    text = re.sub(r"\s*\[Figure data and script\.?\s*\]\([^)]*\)\s*$", "", text)
    return re.sub(r"\s+", " ", text).strip()


def _block(key: str, legend: str) -> str:
    label = _figure_label(key)
    return (
        f"{MARK_A}\n"
        f"## Figure legend — {label}\n\n"
        f"*Verbatim from the manuscript. Generated by\n"
        f"`scripts/figures/sync_readme_legends.py` — edit the manuscript and\n"
        f"re-run; do not hand-edit inside these markers.*\n\n"
        f"> **{label}.** {_clean(legend)}\n"
        f"{MARK_B}"
    )


def _apply(readme: Path, block: str) -> str:
    text = readme.read_text(encoding="utf-8")
    if MARK_A in text:
        return re.sub(
            re.escape(MARK_A) + r".*?" + re.escape(MARK_B), lambda _: block, text, flags=re.S
        )
    lines = text.split("\n")
    i = next(n for n, line in enumerate(lines) if line.startswith("# "))
    j = i + 1
    while j < len(lines) and not lines[j].strip():
        j += 1
    lines.insert(j, block + "\n")
    return "\n".join(lines)


def _cohort_size() -> int | None:
    if not _COHORT_TSV.exists():
        return None
    with _COHORT_TSV.open(encoding="utf-8") as fh:
        return sum(1 for _ in fh) - 1


def _report_stale_counts(legends: dict[str, str]) -> list[str]:
    """Flag legend counts that the shipped data no longer supports.

    Deliberately advisory: it prints, it does not edit. Restating a result
    is the author's call, and a legend can legitimately quote a subset.
    """
    cohort = _cohort_size()
    if cohort is None:
        return []
    notes: list[str] = []
    for key, text in legends.items():
        for m in re.finditer(r"\b([\d]{1,2},[\d]{3})\b", text):
            val = int(m.group(1).replace(",", ""))
            # Only flag numbers presented as the deep-dive cohort.
            window = text[max(0, m.start() - 120) : m.start()]
            if val != cohort and re.search(
                r"cohort|deep[- ]dive[d]?|select|genes for the deep dive", window, re.I
            ):
                notes.append(
                    f"  {key}: legend says {m.group(1)} where the shipped "
                    f"cohort is {cohort:,}"
                )
    return notes


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if any README is out of sync (CI mode); write nothing.",
    )
    args = ap.parse_args()

    payload = json.loads(LEGENDS_JSON.read_text(encoding="utf-8"))
    fig_to_slug: dict[str, str] = payload["figure_to_slug"]
    legends: dict[str, str] = payload["legends"]

    drifted: list[str] = []
    for key, slug in fig_to_slug.items():
        readme = FIG_DIR / f"01_{slug}.md"
        if not readme.exists():
            print(f"!! missing README for {key} ({slug})", file=sys.stderr)
            return 1
        updated = _apply(readme, _block(key, legends[key]))
        if updated != readme.read_text(encoding="utf-8"):
            drifted.append(slug)
            if not args.check:
                readme.write_text(updated, encoding="utf-8")

    if args.check:
        if drifted:
            print(
                "READMEs are out of sync with the manuscript legends:\n  "
                + "\n  ".join(drifted)
                + "\n\nRun: uv run python scripts/figures/sync_readme_legends.py",
                file=sys.stderr,
            )
            return 1
        print(f"all {len(fig_to_slug)} READMEs match the manuscript legends")
    else:
        print(f"synced {len(drifted)} of {len(fig_to_slug)} READMEs")

    notes = _report_stale_counts(legends)
    if notes:
        print(
            "\nAdvisory — legend counts vs the shipped data (not auto-corrected;\n"
            "fix the manuscript, re-export, and re-run):",
            file=sys.stderr,
        )
        print("\n".join(notes), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
