"""Deterministic backfill of executive_summary.{uniprot_family,hgnc_gene_groups}.

One-off maintenance utility for records that predate the v2 family-injection
fix (commit "v2 inject deterministic family tags"). Those records were
generated by a v2 pipeline that never called ``_attach_deterministic_families``,
so they carry ``executive_summary.uniprot_family = None`` and
``hgnc_gene_groups = []`` even for genes that clearly have them (EGFR). The
viewer's deterministic "Family & gene group" bucket then renders nothing.

This script does NOT re-run the LLM. For each requested gene it:

  1. Resolves the family tags from the canonical resolver
     (``resolve_by_hgnc_id`` → ``IdentifierBundle``). These are the same
     curator-assigned ground-truth tags the v2 fix now injects at generation
     time.
  2. Reads the CURRENT record from the public Worker (the record D1 serves).
  3. Mutates ONLY the two family fields under ``executive_summary``, leaving
     everything else (``surface_bind`` etc.) byte-identical.
  4. Republishes via the canonical ``publish_record_dict`` (public D1 +
     in-tree snapshot).

Safety rails:
  * Aborts a gene if the resolver returns empty family (nothing to inject).
  * Aborts a gene if the existing record's ``surface_bind.has_data`` is not
    ``True`` — refuses to backfill family on top of an already-degraded
    record (investigate that separately first).
  * Dry-run by default; ``--execute`` performs the writes.

Usage::

    uv run python scripts/backfill_deterministic_family.py EGFR
    uv run python scripts/backfill_deterministic_family.py EGFR --execute
    uv run python scripts/backfill_deterministic_family.py EGFR CD19 MSLN --execute

Genes are accepted as HGNC symbols; each is resolved to an HGNC ID via D1's
``gene_identifier`` table (same path the annotator uses).
"""

from __future__ import annotations

import argparse
import sys

import httpx

from accessible_surfaceome.cloud.d1_client import D1Client
from accessible_surfaceome.cloud.surface_annotation import publish_record_dict
from accessible_surfaceome.env import load_env
from accessible_surfaceome.tools._shared.http import open_default_client
from accessible_surfaceome.tools.gene_lookup import resolve_by_hgnc_id

WORKER_BASE = "https://api.deliverome.org/surfaceome/v1/genes"


def _hgnc_id_for_symbol(symbol: str) -> str | None:
    """Resolve a gene symbol to its HGNC ID via D1's gene_identifier table."""
    with D1Client() as d1:
        rows = d1.query(
            "SELECT hgnc_id FROM gene_identifier "
            "WHERE hgnc_symbol = ? OR cohort_symbol = ? LIMIT 1;",
            [symbol, symbol],
        )
    return rows[0]["hgnc_id"] if rows else None


def _backfill_one(symbol: str, *, execute: bool, resolver_http, web: httpx.Client) -> bool:
    """Backfill one gene. Returns True on a successful (or dry-run) pass,
    False on an abort.

    ``resolver_http`` is the project ``CachedHTTP`` (for ``resolve_by_hgnc_id``);
    ``web`` is a plain ``httpx.Client`` for the public-Worker GET (CachedHTTP
    has no bare ``.get``)."""
    print(f"\n=== {symbol} ===")
    hgnc_id = _hgnc_id_for_symbol(symbol)
    if not hgnc_id:
        print(f"  ABORT: no hgnc_id for {symbol} in gene_identifier")
        return False

    bundle = resolve_by_hgnc_id(hgnc_id, http=resolver_http)
    uniprot_family = bundle.uniprot_family
    hgnc_gene_groups = list(bundle.hgnc_gene_groups)
    print(f"  resolver uniprot_family   : {uniprot_family!r}")
    print(f"  resolver hgnc_gene_groups : {hgnc_gene_groups!r}")
    if not uniprot_family and not hgnc_gene_groups:
        print("  ABORT: resolver returned empty family — nothing to inject")
        return False

    resp = web.get(f"{WORKER_BASE}/{symbol}", timeout=30)
    resp.raise_for_status()
    rec = resp.json()

    sb = (rec.get("deterministic_features") or {}).get("surface_bind") or {}
    print(f"  existing surface_bind: has_data={sb.get('has_data')} "
          f"n_sites={sb.get('n_sites')}")
    if sb.get("has_data") is not True:
        print("  ABORT: existing surface_bind.has_data is not True — refusing "
              "to backfill family on a degraded record")
        return False

    es = rec.get("executive_summary") or {}
    print(f"  BEFORE uniprot_family={es.get('uniprot_family')!r} "
          f"hgnc_gene_groups={es.get('hgnc_gene_groups')!r}")
    es["uniprot_family"] = uniprot_family
    es["hgnc_gene_groups"] = hgnc_gene_groups
    rec["executive_summary"] = es
    print(f"  AFTER  uniprot_family={es['uniprot_family']!r} "
          f"hgnc_gene_groups={es['hgnc_gene_groups']!r}")

    if not execute:
        print("  DRY-RUN (pass --execute to publish)")
        return True

    result = publish_record_dict(rec, write_snapshot=True)
    print(f"  published: d1_written={result.d1_written} "
          f"snapshot={result.snapshot_path} "
          f"skipped_reason={result.skipped_reason}")
    return result.d1_written


def main() -> int:
    load_env()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("genes", nargs="+", help="HGNC symbol(s) to backfill")
    ap.add_argument(
        "--execute",
        action="store_true",
        help="Publish to D1 + snapshot (default: dry-run)",
    )
    args = ap.parse_args()

    resolver_http = open_default_client()
    web = httpx.Client(timeout=30)
    try:
        ok = all(
            _backfill_one(g, execute=args.execute, resolver_http=resolver_http, web=web)
            for g in args.genes
        )
    finally:
        resolver_http.close()
        web.close()
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
