import catalog from "../../lib/search-catalog.json";
import styles from "./SearchCatalog.module.css";

/**
 * SearchCatalog — documents the searches the two plan_trim_select agents
 * run per gene, shown under the "Deep dive · Phase 1" group header on
 * /prompts so a reader can interpret what an agent's prompt works from.
 *
 * A deterministic kickoff (no LLM planner) runs two agent focuses per gene:
 *   • Surface-evidence agent (A1) — the method-centric assay categories +
 *     structure/topology: HOW the surface call was made.
 *   • Biology agent (A2) — the biology-leaning subset (IHC/IF/flow/mass-spec
 *     + shedding) plus the shared standing axes (normal-tissue tox panel,
 *     subcellular subdomain, etc.): WHERE / WHEN it reaches the surface.
 * Both run the shared literature baselines; the selector may pull follow-ups.
 *
 * The data is generated by `scripts/build/build_search_catalog.py`, which reads the
 * LIVE deterministic kickoff (`build_a1_kickoff` / `build_a2_kickoff`) +
 * `_CATEGORY_SPECS` (→ `viewer/lib/search-catalog.json`), so it can't drift
 * from what the agents actually run.
 */

interface CategoryDef {
  id: string;
  label: string;
  finds: string;
  query_preview: string;
}
interface Baseline {
  id: string;
  label: string;
  finds: string;
}
interface TopicPanel {
  label: string;
  finds: string;
}
interface AgentPlan {
  id: string;
  label: string;
  tagline: string;
  always_category_ids: string[];
  skip_category_ids: string[];
  conditional_note: string;
  always_topic: TopicPanel[];
}

const categories = catalog.categories as Record<string, CategoryDef>;
const baselines = catalog.shared_baselines as Baseline[];
const agents = catalog.agents as AgentPlan[];
const planned = catalog.planned_fill as Baseline[];

function Row({
  label,
  finds,
  query,
}: {
  label: string;
  finds: string;
  query?: string;
}) {
  return (
    <li className={styles.row}>
      <span className={styles.rowLabel}>{label}</span>
      <span className={styles.rowFinds}>{finds}</span>
      {query ? <code className={styles.rowQuery}>{query}</code> : null}
    </li>
  );
}

function AgentColumn({ plan }: { plan: AgentPlan }) {
  const skipped = plan.skip_category_ids
    .map((id) => categories[id]?.label)
    .filter(Boolean);
  return (
    <section className={styles.agent}>
      <header className={styles.agentHead}>
        <h4 className={styles.agentTitle}>{plan.label}</h4>
        <p className={styles.agentTagline}>{plan.tagline}</p>
      </header>

      <p className={styles.subhead}>Always-run assays</p>
      <ul className={styles.list}>
        {plan.always_category_ids.map((id) => {
          const c = categories[id];
          return c ? (
            <Row
              key={id}
              label={c.label}
              finds={c.finds}
              query={c.query_preview}
            />
          ) : null;
        })}
      </ul>

      <p className={styles.subhead}>Always-run topic searches</p>
      <ul className={styles.list}>
        {plan.always_topic.map((t) => (
          <Row key={t.label} label={t.label} finds={t.finds} />
        ))}
      </ul>

      <p className={styles.note}>
        {plan.conditional_note}
        {skipped.length ? (
          <>
            {" "}
            <strong>Skips</strong> {skipped.join(" + ")} — that&rsquo;s the
            other pass&rsquo;s job.
          </>
        ) : null}
      </p>
    </section>
  );
}

export function SearchCatalog() {
  const nAlways =
    baselines.length +
    agents.reduce(
      (n, a) => n + a.always_category_ids.length + a.always_topic.length,
      0,
    );
  return (
    <details className={styles.wrap}>
      <summary className={styles.summary}>
        <span className={styles.summaryTitle}>Searches the agents run</span>
        <span className={styles.summaryHint}>
          two agent focuses · {nAlways} always-run searches · {planned.length}{" "}
          selector follow-ups — click to expand
        </span>
      </summary>
      <div className={styles.body}>
        <p className={styles.lede}>
          Phase 1 runs a <strong>deterministic kickoff</strong> over every gene
          for two agent focuses — the{" "}
          <strong>Surface-evidence agent (A1)</strong> and the{" "}
          <strong>Biology agent (A2)</strong>. There is no LLM planner: each
          focus runs a fixed floor of searches for every gene. Both share the
          literature baselines below; the selector may then pull follow-up
          fetches when the candidate menu has a gap.
        </p>

        <section className={styles.group}>
          <h4 className={styles.groupTitle}>
            Shared literature baselines — both passes, every gene
          </h4>
          <ul className={styles.list}>
            {baselines.map((b) => (
              <Row key={b.id} label={b.label} finds={b.finds} />
            ))}
          </ul>
        </section>

        <div className={styles.agents}>
          {agents.map((a) => (
            <AgentColumn key={a.id} plan={a} />
          ))}
        </div>

        <section className={styles.group}>
          <h4 className={styles.groupTitle}>
            Selector follow-ups — pulled when the menu has a gap
          </h4>
          <p className={styles.groupSub}>
            Not part of the deterministic floor — these are follow-up reads the
            selector requests on top of each focus&rsquo;s fixed search set when
            the candidate menu is missing something.
          </p>
          <ul className={styles.list}>
            {planned.map((m) => (
              <Row key={m.id} label={m.label} finds={m.finds} />
            ))}
          </ul>
        </section>
      </div>
    </details>
  );
}
