"""AUTO-GENERATED by scripts/build_tissue_category_mapping.py. DO NOT EDIT."""

# Anchor UBERON ID per organ-system category — highest-n_total in CZI.
# Build script injects these as zero-signal entries into every gene's
# top_tissues, so the reader always sees the 14 organ systems even when
# the gene has no expression in them.

CATEGORY_ANCHORS = {
    "UBERON:0000955": "cns",  # CNS → brain (n=941,245)
    "UBERON:0000970": "head_sensory",  # Head & sensory → eye (n=57,627)
    "UBERON:0002048": "respiratory",  # Respiratory → lung (n=4,489,452)
    "UBERON:0000948": "cardiovascular",  # Cardiovascular → heart (n=120,581)
    "UBERON:0000178": "lymphoid",  # Lymphoid & blood → blood (n=25,825,191)
    "UBERON:0002107": "hepatobiliary_pancreas",  # Hepatobiliary & pancreas → liver (n=1,236,918)
    "UBERON:0000160": "digestive",  # Digestive (GI) → intestine (n=327,410)
    "UBERON:0002113": "urinary",  # Urinary → kidney (n=943,536)
    "UBERON:0002369": "endocrine",  # Endocrine → adrenal gland (n=543,830)
    "UBERON:0000473": "reproductive",  # Reproductive → testis (n=20,724)
    "UBERON:0002097": "skin_adipose",  # Skin & adipose → skin of body (n=245,931)
    "UBERON:0001134": "musculoskeletal",  # Musculoskeletal → skeletal muscle tissue (n=835)
    "UBERON:0000922": "developmental",  # Developmental → embryo (n=14,244)
    "UBERON:0003688": "fluids_other",  # Fluids / other → omentum (n=222,303)
}

# Flat list for the build script's whitelist injection.
WHITELIST_TISSUES = list(CATEGORY_ANCHORS.keys())
