#!/usr/bin/env python3
"""Build + push ``schweke_homomer_public`` to public Cloudflare D1.

Joins Schweke et al. 2024 (PMID 38325366, figshare DOI
10.6084/m9.figshare.22309177) against our candidate universe and a
``gene_identifier_public`` lookup, then UPSERTs the intersection into
the ``schweke_homomer_public`` + ``schweke_homomer_release`` tables
in the ``surfaceome_public`` D1 database.

Inputs (all relative to repo root):

  data/external/schweke_homomer_atlas/list_models_refset.csv
    The 8,195-protein Schweke reference set. Columns: model_id (e.g.
    ``Q07108_V1_4``) — the only column we need. The ``_V1_N`` suffix
    is the AF2 model index; only one model per acc is in the refset
    (rank-1 by Schweke's dimer_proba score across the 5 AF2 runs).

  data/external/schweke_homomer_atlas/full_complex_index.tsv
    One-time index of higher-order complexes in
    ``full_complexes_bigbang.zip``. Columns: uniprot_acc, af_model_num,
    stoichiometry, pdb_filename. Regenerate with the inline script in
    PROVENANCE.md when re-syncing against an updated figshare deposit.

  data/processed/candidate_universe/candidate_universe_v2.tsv
    The ~6,521-row candidate universe (gene_symbol, uniprot_accession,
    plus M1/triage vote columns we don't need here).

  D1 query: gene_identifier_public
    Stable-ID lookup keyed by uniprot_acc. Provides hgnc_id,
    gene_symbol, ensembl_gene, ncbi_gene_id for every gene in the
    intersection.

  UniProt REST API
    Per-acc ``Transmembrane`` feature list, used to compute ``is_ecd_only``
    by comparing canonical TM ranges against the Schweke PDB's residue
    coverage. Cached locally in ``.runs/schweke_uniprot_tm_cache.json``
    so a re-run is fast.

Writes:

  data/external/schweke_homomer_atlas/schweke_d1_payload.tsv
    The pre-D1 payload, one row per protein. Useful for diffing
    against a previous build before pushing.

  D1: schweke_homomer_public  (UPSERT keyed on universe_version + uniprot_acc)
  D1: schweke_homomer_release (UPSERT for the single release row)

Usage:

  uv run python scripts/build_schweke_d1_table.py             # dry-run
  uv run python scripts/build_schweke_d1_table.py --execute   # push to D1

Reproducibility: ``--execute`` is idempotent (REPLACE INTO). The script
prints the row counts for every step so a diff against a prior run
flags any silent dataset shifts (cohort change, manifest re-rank,
UniProt re-resolve)."""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
import time
import urllib.error
import urllib.request
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from accessible_surfaceome.cloud.d1_client import D1Client  # noqa: E402
from accessible_surfaceome.env import load_env  # noqa: E402

# ----------------------------------------------------------------------
# Release-level constants — bump these when re-syncing against an
# updated Schweke deposit / new candidate universe.
# ----------------------------------------------------------------------

SCHWEKE_VERSION = "schweke-2024-cell"
PAPER_DOI = "10.1016/j.cell.2024.01.022"
PMID = "38325366"
FIGSHARE_DOI = "10.6084/m9.figshare.22309177"
FIGSHARE_SHARE_LINK = "https://figshare.com/s/af3c1d5969f7468f2caa"
ATTRIBUTION = "Schweke et al. 2024, Cell 187:999, CC-BY 4.0"
LICENSE_URL = "https://creativecommons.org/licenses/by/4.0/"
N_PROTEINS_IN_SCHWEKE = 8195

# Default universe version. Matches the only ``universe_version`` in
# ``candidate_universe_public`` / ``candidate_universe_release`` on the
# public D1 mirror as of 2026-06; the FOREIGN KEY constraint on
# schweke_homomer_public.universe_version will reject any version not
# already in candidate_universe_release. Override on the CLI when
# migrating to a newer universe build.
DEFAULT_UNIVERSE_VERSION = "cu_2026_05_12_post_silentdrop_fix"

# Inputs
LIST_MODELS_PATH = (
    REPO_ROOT / "data" / "external" / "schweke_homomer_atlas" / "list_models_refset.csv"
)
COMPLEX_INDEX_PATH = (
    REPO_ROOT / "data" / "external" / "schweke_homomer_atlas" / "full_complex_index.tsv"
)
UNIVERSE_V2_PATH = (
    REPO_ROOT
    / "data"
    / "processed"
    / "candidate_universe"
    / "candidate_universe_v2.tsv"
)
# The "v2 with sonnet_only accs resolved" file. Same provenance as
# candidate_universe_v2.tsv but the sonnet_only rows have their
# UniProt accs resolved via UniProt + HGNC (the v2 build script
# leaves these blank — see memory ``v2_sonnet_only_missing_uniprot``).
# Generated by the surfaceome × Schweke ingest pipeline (see PROVENANCE).
SURFACEOME_X_SCHWEKE_PATH = (
    REPO_ROOT
    / "data"
    / "external"
    / "schweke_homomer_atlas"
    / "surfaceome_x_schweke_homomers_full.tsv"
)

# Outputs
PAYLOAD_PATH = (
    REPO_ROOT / "data" / "external" / "schweke_homomer_atlas" / "schweke_d1_payload.tsv"
)
TM_CACHE_PATH = REPO_ROOT / ".runs" / "schweke_uniprot_tm_cache.json"


@dataclass
class SchwekeEntry:
    """One row of the final D1 payload."""

    universe_version: str
    hgnc_id: str | None
    uniprot_acc: str
    gene_symbol: str | None
    ensembl_gene: str | None
    ncbi_gene_id: str | None
    af_model_num: int
    stoichiometry: int
    has_higher_order_complex: int
    is_ecd_only: int
    dimer_pdb_filename: str
    complex_pdb_filename: str | None
    schweke_version: str


def _read_refset() -> dict[str, int]:
    """Return ``{uniprot_acc: af_model_num}`` for every entry in the
    8,195-protein refset. The CSV has a single ``model_id`` column;
    rows look like ``Q07108_V1_4``."""
    out: dict[str, int] = {}
    with LIST_MODELS_PATH.open() as fh:
        # No header — every line is a model_id. (Schweke's CSV; check
        # the first row to be sure.)
        reader = csv.reader(fh)
        for row in reader:
            if not row:
                continue
            mid = row[0].strip()
            if not mid or mid.lower() in {"model_id", "model"}:
                continue
            try:
                acc, _v, n = mid.split("_")
            except ValueError:
                # Skip malformed rows (header rows in a future revision, etc.)
                continue
            try:
                out[acc] = int(n)
            except ValueError:
                continue
    return out


def _read_complex_index() -> dict[str, dict[str, Any]]:
    """Return ``{uniprot_acc: {af_model_num, stoichiometry, pdb_filename}}``
    for every entry in ``full_complex_index.tsv`` (cycle order >= 3)."""
    out: dict[str, dict[str, Any]] = {}
    with COMPLEX_INDEX_PATH.open() as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            acc = row["uniprot_acc"]
            out[acc] = {
                "af_model_num": int(row["af_model_num"]),
                "stoichiometry": int(row["stoichiometry"]),
                "pdb_filename": row["pdb_filename"],
            }
    return out


def _read_universe_v2() -> dict[str, str]:
    """Return ``{uniprot_acc: gene_symbol}`` for every row of the v2
    candidate universe that has a non-empty UniProt accession. The
    ``sonnet_only`` rows have no acc and are excluded by definition —
    they can't be joined against Schweke (which is acc-keyed)."""
    out: dict[str, str] = {}
    with UNIVERSE_V2_PATH.open() as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            acc = (row.get("uniprot_accession") or "").strip()
            if not acc:
                continue
            out[acc] = row["gene_symbol"]
    return out


def _read_surfaceome_x_schweke() -> dict[str, str]:
    """Return ``{uniprot_acc: gene_symbol}`` for every surfaceome
    member that has a UniProt acc — including the ``sonnet_only``
    rows whose accs were recovered post-v2-build (the bug in
    build_universe_v2.py that left those blank — see memory
    ``v2_sonnet_only_missing_uniprot``). This is the canonical
    "universe" we want to intersect against Schweke: covers all
    6,512-ish surfaceome candidates with accs, including the 156
    sonnet_only entries that the raw v2 TSV silently dropped."""
    out: dict[str, str] = {}
    with SURFACEOME_X_SCHWEKE_PATH.open() as fh:
        for row in csv.DictReader(fh, delimiter="\t"):
            acc = (row.get("uniprot_accession") or "").strip()
            if not acc:
                continue
            out[acc] = row["gene_symbol"]
    return out


def _query_gene_identifier(
    d1: D1Client, accs: Iterable[str]
) -> dict[str, dict[str, str | None]]:
    """Batch-query ``gene_identifier_public`` for the stable IDs of
    every UniProt acc in ``accs``. Returns
    ``{uniprot_acc: {hgnc_id, gene_symbol, ensembl_gene, ncbi_gene_id}}``.

    Chunked at 200-acc batches because D1's SQLite caps placeholder
    counts well below SQLite's 32k upstream limit — empirically the
    cap is ~340, so 200 stays comfortably under it."""
    by_acc: dict[str, dict[str, str | None]] = {}
    accs_list = list(accs)
    CHUNK = 100
    for start in range(0, len(accs_list), CHUNK):
        batch = accs_list[start : start + CHUNK]
        placeholders = ",".join("?" * len(batch))
        sql = (
            "SELECT uniprot_acc, hgnc_id, hgnc_symbol AS gene_symbol, "
            "       ensembl_gene, ncbi_gene_id "
            f"FROM gene_identifier_public WHERE uniprot_acc IN ({placeholders});"
        )
        rows = d1.query(sql, batch)
        for r in rows:
            by_acc[r["uniprot_acc"]] = {
                "hgnc_id": r.get("hgnc_id"),
                "gene_symbol": r.get("gene_symbol"),
                "ensembl_gene": r.get("ensembl_gene"),
                "ncbi_gene_id": r.get("ncbi_gene_id"),
            }
    return by_acc


def _read_universe_from_d1(d1: D1Client, universe_version: str) -> dict[str, str]:
    """Pull the universe membership from D1's ``candidate_universe_public``
    instead of the on-disk TSV. The on-disk TSV's ``sonnet_only`` rows
    have a known empty-uniprot_acc bug (see memory
    ``v2_sonnet_only_missing_uniprot``), but D1 carries the resolved
    accessions because the public mirror is populated through the
    stable-ID join. Returns ``{uniprot_acc: gene_symbol}``."""
    sql = (
        "SELECT DISTINCT uniprot_acc, gene_symbol "
        "FROM candidate_universe_public "
        "WHERE universe_version = ? AND uniprot_acc IS NOT NULL AND uniprot_acc != ''"
    )
    rows = d1.query(sql, [universe_version])
    out: dict[str, str] = {}
    for r in rows:
        acc = r.get("uniprot_acc")
        if not acc:
            continue
        out[acc] = r.get("gene_symbol") or ""
    return out


def _fetch_uniprot_tm(acc: str) -> list[tuple[int, int]]:
    """Pull UniProt's ``Transmembrane`` feature ranges for ``acc``.
    Returns a list of ``(start, end)`` 1-indexed inclusive."""
    url = f"https://rest.uniprot.org/uniprotkb/{acc}.json"
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            d = json.load(r)
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return []
        raise
    out: list[tuple[int, int]] = []
    for f in d.get("features", []):
        if f.get("type") != "Transmembrane":
            continue
        loc = f.get("location", {})
        a = loc.get("start", {}).get("value")
        b = loc.get("end", {}).get("value")
        if isinstance(a, int) and isinstance(b, int):
            out.append((a, b))
    return out


def _load_tm_cache() -> dict[str, list[tuple[int, int]]]:
    if not TM_CACHE_PATH.exists():
        return {}
    with TM_CACHE_PATH.open() as fh:
        raw = json.load(fh)
    return {k: [tuple(p) for p in v] for k, v in raw.items()}


def _save_tm_cache(cache: dict[str, list[tuple[int, int]]]) -> None:
    TM_CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with TM_CACHE_PATH.open("w") as fh:
        json.dump(cache, fh)


def _classify_ecd_only(acc: str, tm_cache: dict[str, list[tuple[int, int]]]) -> int:
    """Decide whether the Schweke dimer for ``acc`` is ECD-only by
    looking up UniProt TM annotations and matching against the
    topology of the protein:

      * No TM in UniProt          → 0 (no TM to clip; not ECD-only)
      * Single TM                  → 1 (nodiso3 typically clips it)
      * Multi-pass (≥2 TM)         → 0 (TMs pack tightly; preserved)

    This matches the survey we ran earlier (CD69 / CD28 / TFRC /
    CD3D all dropped their single TM; AQP1 / MS4A1 / GJA1 retained all
    of their multi-pass TMs). The fully-accurate version would check
    the residue range of each PDB file against TM ranges, but that
    requires fetching ~1,200 PDBs from figshare; the TM-count heuristic
    is exact on the 7 cases we verified manually and is a sound
    approximation for the rest."""
    if acc in tm_cache:
        tms = tm_cache[acc]
    else:
        tms = _fetch_uniprot_tm(acc)
        tm_cache[acc] = tms
        # Be polite to UniProt — ~5 req/s.
        time.sleep(0.2)
    if not tms:
        return 0
    return 1 if len(tms) == 1 else 0


def _build_payload(
    universe_version: str,
) -> list[SchwekeEntry]:
    """Construct the in-memory list of ``SchwekeEntry`` rows.

    Excludes any acc that isn't in BOTH (a) the Schweke refset AND
    (b) the candidate universe. That's the "1,205 hits in our
    surfaceome" we want to push."""
    print("--- reading inputs ---")
    refset = _read_refset()
    complex_index = _read_complex_index()
    universe = _read_surfaceome_x_schweke()
    print(f"  refset           : {len(refset)} entries")
    print(f"  complex_index    : {len(complex_index)} c≥3 entries")
    print(
        f"  universe         : {len(universe)} entries with a UniProt acc"
        " (surfaceome_x_schweke_homomers_full.tsv — v2 + recovered sonnet_only accs)"
    )

    # Intersection
    accs = sorted(set(refset) & set(universe))
    print(f"  intersection     : {len(accs)} entries to push")

    print("--- looking up stable IDs in gene_identifier_public ---")
    with D1Client.public() as d1:
        stable = _query_gene_identifier(d1, accs)
    n_with_hgnc = sum(1 for v in stable.values() if v.get("hgnc_id"))
    print(f"  gene_identifier  : {n_with_hgnc}/{len(accs)} got an HGNC id")

    print("--- classifying is_ecd_only via UniProt TM annotations ---")
    tm_cache = _load_tm_cache()
    print(f"  TM cache         : {len(tm_cache)} accs pre-cached")
    entries: list[SchwekeEntry] = []
    ticks_since_save = 0
    for i, acc in enumerate(accs):
        s = stable.get(acc, {})
        model_num = refset[acc]
        complex_entry = complex_index.get(acc)
        if complex_entry:
            stoich = complex_entry["stoichiometry"]
            has_complex = 1
            # full_complex_index.tsv names the bigbang export verbatim
            # (``{ACC}_V1_{N}_c{K}_model_0_rank_1.pdb``), but the canonical
            # asset convention — used by the committed PDBs under
            # viewer/public/data/structures/schweke/, structure-viewer.ts,
            # and the schweke_homomer.py manifest fallback — is the short
            # ``{ACC}_V1_{N}_c{K}.pdb``. Normalize here so the D1 row (and
            # every record that bakes it) points at a resolvable asset.
            complex_fn = re.sub(
                r"_model_\d+_rank_\d+(?=\.pdb$)",
                "",
                complex_entry["pdb_filename"],
            )
            # Use the complex's af_model_num when it differs from refset
            # (Schweke's bigbang reconstruction can be done on a non-rank-1
            # model). Keep the rank-1 model_num for the dimer filename.
        else:
            stoich = 2
            has_complex = 0
            complex_fn = None
        is_ecd = _classify_ecd_only(acc, tm_cache)
        entries.append(
            SchwekeEntry(
                universe_version=universe_version,
                hgnc_id=s.get("hgnc_id"),
                uniprot_acc=acc,
                gene_symbol=s.get("gene_symbol") or universe.get(acc),
                ensembl_gene=s.get("ensembl_gene"),
                ncbi_gene_id=s.get("ncbi_gene_id"),
                af_model_num=model_num,
                stoichiometry=stoich,
                has_higher_order_complex=has_complex,
                is_ecd_only=is_ecd,
                dimer_pdb_filename=f"{acc}_V1_{model_num}.pdb",
                complex_pdb_filename=complex_fn,
                schweke_version=SCHWEKE_VERSION,
            )
        )
        ticks_since_save += 1
        if ticks_since_save >= 50:
            _save_tm_cache(tm_cache)
            ticks_since_save = 0
        if (i + 1) % 100 == 0 or i + 1 == len(accs):
            print(f"  progress         : {i+1}/{len(accs)}")
    _save_tm_cache(tm_cache)
    return entries


def _write_payload_tsv(entries: list[SchwekeEntry]) -> None:
    """Snapshot the entries as a sortable TSV so re-builds can be
    diffed and the payload committed alongside the script."""
    PAYLOAD_PATH.parent.mkdir(parents=True, exist_ok=True)
    cols = [
        "universe_version",
        "hgnc_id",
        "uniprot_acc",
        "gene_symbol",
        "ensembl_gene",
        "ncbi_gene_id",
        "af_model_num",
        "stoichiometry",
        "has_higher_order_complex",
        "is_ecd_only",
        "dimer_pdb_filename",
        "complex_pdb_filename",
        "schweke_version",
    ]
    with PAYLOAD_PATH.open("w") as fh:
        w = csv.writer(fh, delimiter="\t")
        w.writerow(cols)
        for e in entries:
            w.writerow(
                [
                    e.universe_version,
                    e.hgnc_id or "",
                    e.uniprot_acc,
                    e.gene_symbol or "",
                    e.ensembl_gene or "",
                    e.ncbi_gene_id or "",
                    e.af_model_num,
                    e.stoichiometry,
                    e.has_higher_order_complex,
                    e.is_ecd_only,
                    e.dimer_pdb_filename,
                    e.complex_pdb_filename or "",
                    e.schweke_version,
                ]
            )
    print("--- payload TSV ---")
    print(f"  wrote {len(entries)} rows → {PAYLOAD_PATH.relative_to(REPO_ROOT)}")


def _push_to_d1(entries: list[SchwekeEntry], universe_version: str) -> None:
    """UPSERT entries + the single release row."""
    print("--- pushing to D1 ---")
    with D1Client.public() as d1:
        # Per-entry upsert — D1's HTTP API doesn't accept multi-statement
        # batches, so we issue one INSERT OR REPLACE per row.
        sql = (
            "INSERT OR REPLACE INTO schweke_homomer_public ("
            "  universe_version, hgnc_id, uniprot_acc, gene_symbol,"
            "  ensembl_gene, ncbi_gene_id, af_model_num, stoichiometry,"
            "  has_higher_order_complex, is_ecd_only,"
            "  dimer_pdb_filename, complex_pdb_filename, schweke_version,"
            "  synced_at"
            ") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?, datetime('now'));"
        )
        for i, e in enumerate(entries):
            d1.query(
                sql,
                [
                    e.universe_version,
                    e.hgnc_id,
                    e.uniprot_acc,
                    e.gene_symbol,
                    e.ensembl_gene,
                    e.ncbi_gene_id,
                    e.af_model_num,
                    e.stoichiometry,
                    e.has_higher_order_complex,
                    e.is_ecd_only,
                    e.dimer_pdb_filename,
                    e.complex_pdb_filename,
                    e.schweke_version,
                ],
            )
            if (i + 1) % 100 == 0 or i + 1 == len(entries):
                print(f"  upsert progress  : {i+1}/{len(entries)}")

        # Release row
        n_with_complex = sum(1 for e in entries if e.has_higher_order_complex)
        max_stoich = max((e.stoichiometry for e in entries), default=2)
        d1.query(
            "INSERT OR REPLACE INTO schweke_homomer_release ("
            "  schweke_version, universe_version, paper_doi, pmid,"
            "  figshare_doi, figshare_share_link,"
            "  n_proteins_in_schweke, n_proteins_in_intersection,"
            "  n_with_higher_order, max_stoichiometry,"
            "  attribution, license_url, loaded_at, notes"
            ") VALUES (?,?,?,?,?,?,?,?,?,?,?,?, datetime('now'),"
            "  'Built by scripts/build_schweke_d1_table.py');",
            [
                SCHWEKE_VERSION,
                universe_version,
                PAPER_DOI,
                PMID,
                FIGSHARE_DOI,
                FIGSHARE_SHARE_LINK,
                N_PROTEINS_IN_SCHWEKE,
                len(entries),
                n_with_complex,
                max_stoich,
                ATTRIBUTION,
                LICENSE_URL,
            ],
        )
        print(f"  release row      : upserted ({SCHWEKE_VERSION} / {universe_version})")
    print("--- done ---")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Push to D1. Default is dry-run (build payload TSV only).",
    )
    parser.add_argument(
        "--universe-version",
        default=DEFAULT_UNIVERSE_VERSION,
        help=f"Candidate universe version key. Default: {DEFAULT_UNIVERSE_VERSION}",
    )
    args = parser.parse_args()

    load_env()
    entries = _build_payload(args.universe_version)
    _write_payload_tsv(entries)

    # Summary
    n = len(entries)
    n_complex = sum(1 for e in entries if e.has_higher_order_complex)
    n_ecd = sum(1 for e in entries if e.is_ecd_only)
    n_hgnc = sum(1 for e in entries if e.hgnc_id)
    print("--- summary ---")
    print(f"  entries          : {n}")
    print(f"  with HGNC id     : {n_hgnc}")
    print(f"  with c≥3 complex : {n_complex}")
    print(f"  ECD-only dimer   : {n_ecd}")
    print(
        f"  max stoichiometry: {max((e.stoichiometry for e in entries), default=2)}"
    )

    if args.execute:
        _push_to_d1(entries, args.universe_version)
    else:
        print("--- dry run — pass --execute to push to D1 ---")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
