"""Sync tag-sites JSON -> public D1's ``tag_site_public``.

Reads every ``viewer/public/tag-sites/{SYMBOL}.json`` (the deterministic +
literature pipelines' committed output) and UPSERTs one row per site via
:func:`accessible_surfaceome.cloud.tag_sites.publish_tag_sites` (idempotent;
replace-all per gene). Env comes from ``.env`` via ``load_env``
(``CLOUDFLARE_D1_SURFACEOME_PUBLIC_ID`` etc.).

    uv run python scripts/sync_tag_sites_to_d1.py --dry-run
    uv run python scripts/sync_tag_sites_to_d1.py --version 2026-08-15
    uv run python scripts/sync_tag_sites_to_d1.py --gene TFRC --version 2026-08-15
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

from accessible_surfaceome.cloud import tag_sites as tag_sites_d1
from accessible_surfaceome.cloud.d1_client import D1Client
from accessible_surfaceome.env import load_env
from accessible_surfaceome.paths import REPO_ROOT

log = logging.getLogger("sync_tag_sites")
TAG_SITES_DIR = REPO_ROOT / "viewer" / "public" / "tag-sites"


def _files(gene: str | None, manifest: str | None = None) -> list[Path]:
    """The JSON files to publish: one gene, a manifest's genes, or the whole store.

    A manifest matters when only part of the store should move. ``publish_tag_sites``
    replaces all rows for the genes it is given and leaves every other gene alone, so
    scoping the file list is what keeps an unrelated gene's published rows untouched --
    for instance when the rest of the store was generated by an earlier pipeline and
    should not be restamped with this run's version.
    """
    files = sorted(TAG_SITES_DIR.glob("*.json"))
    if gene:
        return [f for f in files if f.stem == gene]
    if manifest:
        wanted = {
            line.split("\t")[0].strip()
            for line in Path(manifest).read_text().splitlines()
            if line.strip() and not line.startswith("#")
        }
        picked = [f for f in files if f.stem in wanted]
        missing = wanted - {f.stem for f in picked}
        if missing:
            log.warning("%d manifest gene(s) have no JSON in the store: %s",
                        len(missing), ", ".join(sorted(missing)[:10]))
        return picked
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--dry-run", action="store_true",
        help="parse + count the rows that WOULD be written; write nothing.",
    )
    ap.add_argument(
        "--version", default="dev",
        help="tag_sites_version stamp for these rows (e.g. a date).",
    )
    ap.add_argument("--allow-deletes", action="store_true",
                    help="proceed even when a gene's local JSON has FEWER sites than "
                         "D1 holds (replace-all would delete the difference).")
    ap.add_argument("--gene", help="sync only this SYMBOL (default: all committed JSON).")
    ap.add_argument("--manifest", help="TSV whose first column is a gene SYMBOL; sync "
                                       "only those genes, leaving the rest of the store "
                                       "unpublished and unstamped.")
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    files = _files(args.gene, args.manifest)
    if not files:
        log.warning("no tag-sites JSON found in %s", TAG_SITES_DIR)
        return 1

    if args.dry_run:
        total = 0
        for f in files:
            data = json.loads(f.read_text())
            rows = tag_sites_d1.rows_for_file(data, version=args.version, synced_at="(dry-run)")
            total += len(rows)
            log.info("%-12s %3d sites", data["gene_symbol"], len(rows))
        log.info("dry-run: %d gene(s), %d site row(s) — nothing written", len(files), total)
        return 0

    load_env()
    client = D1Client.public()

    # Pre-flight: publish_tag_sites is REPLACE-ALL per gene, so syncing a stale
    # snapshot DELETES rows D1 holds and the file does not. The dry-run counts
    # what would be written and says nothing about what would be destroyed —
    # which is how a sync from snapshots that had already drifted removed 40
    # live rows, including every deterministic site for a gene the in-tree JSON
    # had lost at an earlier commit.
    shrinking: list[tuple[str, int, int]] = []
    for path in files:
        data = json.loads(path.read_text())
        symbol = data.get("gene_symbol") or path.stem
        local_n = len(data.get("sites") or [])
        rows = client.query(
            "SELECT COUNT(*) n FROM tag_site_public WHERE gene_symbol = ?;", [symbol]
        )
        remote_n = (rows[0]["n"] if rows else 0) or 0
        if remote_n > local_n:
            shrinking.append((symbol, remote_n, local_n))
    if shrinking and not args.allow_deletes:
        log.error(
            "REFUSING: %d gene(s) would LOSE rows — D1 holds more sites than the "
            "local JSON. Re-derive the missing sites (scripts/regenerate_tag_sites.py) "
            "or pass --allow-deletes if the removal is intended.",
            len(shrinking),
        )
        for symbol, remote_n, local_n in shrinking[:20]:
            log.error("    %-10s D1=%d local=%d  (-%d)", symbol, remote_n, local_n,
                      remote_n - local_n)
        return 2
    if shrinking:
        log.warning("--allow-deletes: %d gene(s) will lose rows", len(shrinking))

    try:
        tag_sites_d1.ensure_table(client)
        grand = 0
        for f in files:
            data = json.loads(f.read_text())
            n = tag_sites_d1.publish_tag_sites(
                data, tag_sites_version=args.version, client=client
            )
            grand += n
            log.info("synced %-12s %3d sites", data["gene_symbol"], n)
        log.info("done: %d gene(s), %d site row(s) -> tag_site_public", len(files), grand)
    finally:
        client.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
