"""SURFACE-Bind per-UniProt lookup helper.

Reads the checked-in summary JSON
(``data/external/surface_bind/surface_bind_summary.json``,
regenerated by ``scripts/build_surface_bind_summary.py``) and exposes
a :func:`lookup` returning the :class:`SurfaceBindFeatures` block for
any UniProt accession.

Pattern mirrors :mod:`tools.afdb_plddt`: pure lookup, no network calls
on the orchestrator hot path. The summary file is small (~330 KB,
~2,500 entries) and loaded once into a module-level cache.

When a UniProt accession isn't in the summary, returns a default
:class:`SurfaceBindFeatures` with ``has_data=False`` — the explicit
"not in SURFACE-Bind" signal that the catalog can filter on.

References:
    Marchand A, Khakzad H, et al. Mapping targetable sites on the
    human surfaceome for the design of novel binders. PNAS 2026.
    https://doi.org/10.1073/pnas.2506269123
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from accessible_surfaceome.tools._shared.models import (
    SurfaceBindFeatures,
    SurfaceBindSite,
)

logger = logging.getLogger(__name__)

# Resolves relative to the repo root rather than the package, because
# the summary is repo-data not package-data.
SUMMARY_PATH = (
    Path(__file__).resolve().parents[3]
    / "data" / "external" / "surface_bind" / "surface_bind_summary.json"
)

_CACHE: dict[str, dict[str, Any]] | None = None


def _load() -> dict[str, dict[str, Any]]:
    """Lazy-load the summary JSON into a module-level cache.

    The summary is checked into git (~330 KB), so this is a single
    disk read on first call. Returns an empty dict + logs a warning
    if the file is missing — the lookup falls through to "no data"
    in that case so the orchestrator never crashes on a missing
    auxiliary file.
    """
    global _CACHE
    if _CACHE is not None:
        return _CACHE
    if not SUMMARY_PATH.exists():
        logger.warning(
            "SURFACE-Bind summary missing at %s; lookups will return "
            "has_data=False. Regenerate with "
            "`uv run python scripts/build_surface_bind_summary.py`.",
            SUMMARY_PATH,
        )
        _CACHE = {}
        return _CACHE
    try:
        payload = json.loads(SUMMARY_PATH.read_text())
    except json.JSONDecodeError as exc:
        logger.warning("SURFACE-Bind summary unparseable (%s); ignoring", exc)
        _CACHE = {}
        return _CACHE
    # Drop the __meta__ wrapper before caching.
    _CACHE = {k: v for k, v in payload.items() if k != "__meta__"}
    logger.info("loaded SURFACE-Bind summary: %d entries", len(_CACHE))
    return _CACHE


def lookup(uniprot_acc: str) -> SurfaceBindFeatures:
    """Return the SURFACE-Bind summary block for ``uniprot_acc``.

    Returns a default :class:`SurfaceBindFeatures` (``has_data=False``)
    when the accession isn't in the summary — that's the explicit
    "not in SURFACE-Bind" signal, distinct from "SURFACE-Bind hasn't
    been ingested yet" (which would be the empty-cache case).

    ``has_data`` is set to ``True`` whenever the protein appears in
    SURFACE-Bind's authoritative ``results_no_TM.csv`` even when the
    per-site array is empty (the protein got scored but no patches
    cleared the targetability threshold — a real "no good binder
    sites" signal). Use ``len(sites) > 0`` to distinguish "scored
    with sites" from "scored without sites".
    """
    cache = _load()
    entry = cache.get(uniprot_acc)
    if entry is None:
        return SurfaceBindFeatures(has_data=False)
    sites = [
        SurfaceBindSite(
            site_id=int(s["site_id"]),
            anchor_residue=int(s["anchor_residue"]),
            area_a2=float(s["area_a2"]),
            n_seeds_alpha=int(s["n_seeds_alpha"]),
            n_seeds_beta=int(s["n_seeds_beta"]),
            hydrophobicity=float(s["hydrophobicity"]),
        )
        for s in entry.get("sites", [])
    ]
    return SurfaceBindFeatures(
        has_data=True,
        n_sites=int(entry.get("n_sites", 0)),
        n_seeds_alpha=int(entry.get("n_seeds_alpha", 0)),
        n_seeds_beta=int(entry.get("n_seeds_beta", 0)),
        n_seeds_total=int(entry.get("n_seeds_total", 0)),
        chain=entry.get("chain"),
        sites=sites,
        main_class=entry.get("main_class"),
        sub_class=entry.get("sub_class"),
        protein_name=entry.get("protein_name"),
        pdbs=list(entry.get("pdbs", [])),
    )
