"""SURFACE-Bind per-UniProt lookup helper.

Returns a :class:`SurfaceBindFeatures` block for any UniProt accession,
populated from SURFACE-Bind's published ``results_no_TM.csv`` data
(Balbi et al. 2026 PNAS — PMID 41604262 / DOI 10.1073/pnas.2506269123).

Data source resolution order (first one with the gene wins):

1. **Public D1** ``surface_bind_protein`` + ``surface_bind_site`` tables —
   the canonical source. Pushed by ``scripts/sync_surface_bind_to_d1.py``;
   read by this module via :class:`D1Client.public`. When the D1 query
   fails (table missing / no row / D1 unreachable / env vars absent),
   we fall through silently to the JSON snapshot below.
2. **Checked-in summary JSON**
   ``data/external/surface_bind/surface_bind_summary.json`` —
   ~330 KB / ~2,500 entries, regenerated by
   ``scripts/build_surface_bind_summary.py``. Offline / CI-friendly
   fallback; used when D1 isn't reachable (no CLOUDFLARE_* env vars in
   the worktree, or temporary network blip).
3. **Default** :class:`SurfaceBindFeatures` with ``has_data=False`` —
   the explicit "not in SURFACE-Bind" signal that the catalog can filter
   on, distinct from "SURFACE-Bind hasn't been ingested yet" (which
   would be the empty-cache case).

Pattern mirrors :mod:`tools.schweke_homomer`: pure lookup, D1-first
with a static-file fallback, defaults last. The JSON is loaded once into
a module-level cache so re-lookups don't re-read disk.

References:
    Balbi PEM, Sadek A, Marchand A, et al. Mapping targetable sites on the
    human surfaceome for the design of novel binders. PNAS 2026.
    https://doi.org/10.1073/pnas.2506269123
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from accessible_surfaceome.tools._shared.models import (
    SurfaceBindFeatures,
    SurfaceBindSite,
)

logger = logging.getLogger(__name__)

# Resolves relative to the repo root rather than the package, because
# the summary is repo-data not package-data.
SUMMARY_PATH = (
    Path(__file__).resolve().parents[3]
    / "data" / "external" / "surface_bind" / "surface_bind_summary.json"
)

_CACHE: dict[str, dict[str, Any]] | None = None


def _load() -> dict[str, dict[str, Any]]:
    """Lazy-load the summary JSON into a module-level cache.

    The summary is checked into git (~330 KB), so this is a single
    disk read on first call. Returns an empty dict + logs a warning
    if the file is missing — the lookup falls through to "no data"
    in that case so the orchestrator never crashes on a missing
    auxiliary file.
    """
    global _CACHE
    if _CACHE is not None:
        return _CACHE
    if not SUMMARY_PATH.exists():
        logger.warning(
            "SURFACE-Bind summary missing at %s; lookups will return "
            "has_data=False. Regenerate with "
            "`uv run python scripts/build_surface_bind_summary.py`.",
            SUMMARY_PATH,
        )
        _CACHE = {}
        return _CACHE
    try:
        payload = json.loads(SUMMARY_PATH.read_text())
    except json.JSONDecodeError as exc:
        logger.warning("SURFACE-Bind summary unparseable (%s); ignoring", exc)
        _CACHE = {}
        return _CACHE
    # Drop the __meta__ wrapper before caching.
    _CACHE = {k: v for k, v in payload.items() if k != "__meta__"}
    logger.info("loaded SURFACE-Bind summary: %d entries", len(_CACHE))
    return _CACHE


def _decode_pdbs(raw: Any) -> list[str]:
    """Decode the ``pdbs`` column from D1 into a list of strings.

    The sync script (``scripts/sync_surface_bind_to_d1.py``) stores the
    column as ``json.dumps(entry.get("pdbs", []))`` — a JSON-encoded
    array of strings. Defensively accept the rare list shape, an empty /
    null cell, and a comma-separated string (older snapshots) so a
    schema rev can't silently drop the PDB list.
    """
    if raw is None or raw == "":
        return []
    if isinstance(raw, list):
        return [str(x) for x in raw if x]
    if isinstance(raw, str):
        s = raw.strip()
        if not s:
            return []
        # JSON-encoded list — the canonical shape sync_surface_bind_to_d1.py
        # writes today.
        if s.startswith("["):
            try:
                decoded = json.loads(s)
                if isinstance(decoded, list):
                    return [str(x) for x in decoded if x]
            except json.JSONDecodeError:
                pass
        # Fall back to comma-separated.
        return [tok.strip() for tok in s.split(",") if tok.strip()]
    return []


def _lookup_d1(uniprot_acc: str) -> SurfaceBindFeatures | None:
    """Try the public-D1 ``surface_bind_protein`` + ``surface_bind_site`` tables.

    Returns ``None`` on any failure (table missing / D1 unreachable / no
    row / env vars absent) so the caller falls through to the JSON
    snapshot path. ``None`` from the D1 path means "we didn't find
    SURFACE-Bind metadata HERE" — NOT "the protein isn't scored" (that's
    expressed as a real return value with ``has_data=False``).

    There is no separate ``surface_bind_release`` table; ``uniprot_acc``
    is the PRIMARY KEY on ``surface_bind_protein`` (one row per acc), so
    a single ``LIMIT 1`` is enough. ``ORDER BY surfacebind_version DESC``
    is included defensively in case the schema later relaxes the unique
    key to allow multi-version coexistence.
    """
    try:
        from accessible_surfaceome.cloud.d1_client import D1Client
    except ImportError:  # pragma: no cover — D1 client always available in CI
        return None
    try:
        with D1Client.public() as d1:
            protein_rows = d1.query(
                "SELECT chain, main_class, sub_class, protein_name, n_sites, "
                "n_seeds_alpha, n_seeds_beta, n_seeds_total, pdbs "
                "FROM surface_bind_protein WHERE uniprot_acc = ? "
                "ORDER BY surfacebind_version DESC LIMIT 1;",
                [uniprot_acc],
            )
            if not protein_rows:
                # The query succeeded but the protein isn't in SURFACE-Bind's
                # scored set — the explicit "not scored" signal. Return a
                # real default rather than ``None`` so the JSON fallback
                # doesn't get to second-guess D1's authoritative answer.
                return SurfaceBindFeatures(has_data=False)
            p = protein_rows[0]
            site_rows = d1.query(
                "SELECT site_id, anchor_residue, area_a2, n_seeds_alpha, "
                "n_seeds_beta, hydrophobicity "
                "FROM surface_bind_site WHERE uniprot_acc = ? "
                "ORDER BY site_id;",
                [uniprot_acc],
            )
    except Exception:  # noqa: BLE001 — env / table / network errors fall through
        return None

    sites = [
        SurfaceBindSite(
            site_id=int(s["site_id"]),
            anchor_residue=int(s["anchor_residue"]),
            area_a2=float(s["area_a2"]),
            n_seeds_alpha=int(s["n_seeds_alpha"]),
            n_seeds_beta=int(s["n_seeds_beta"]),
            hydrophobicity=float(s["hydrophobicity"]),
        )
        for s in site_rows
    ]
    return SurfaceBindFeatures(
        has_data=True,
        n_sites=int(p.get("n_sites") or 0),
        n_seeds_alpha=int(p.get("n_seeds_alpha") or 0),
        n_seeds_beta=int(p.get("n_seeds_beta") or 0),
        n_seeds_total=int(p.get("n_seeds_total") or 0),
        chain=p.get("chain"),
        sites=sites,
        main_class=p.get("main_class"),
        sub_class=p.get("sub_class"),
        protein_name=p.get("protein_name"),
        pdbs=_decode_pdbs(p.get("pdbs")),
    )


def _lookup_json(uniprot_acc: str) -> SurfaceBindFeatures:
    """Return the SURFACE-Bind block for ``uniprot_acc`` from the JSON fallback.

    Returns a default :class:`SurfaceBindFeatures` (``has_data=False``)
    when the accession isn't in the summary — the explicit "not in
    SURFACE-Bind" signal, distinct from "SURFACE-Bind hasn't been
    ingested yet" (which would be the empty-cache case).
    """
    cache = _load()
    entry = cache.get(uniprot_acc)
    if entry is None:
        return SurfaceBindFeatures(has_data=False)
    sites = [
        SurfaceBindSite(
            site_id=int(s["site_id"]),
            anchor_residue=int(s["anchor_residue"]),
            area_a2=float(s["area_a2"]),
            n_seeds_alpha=int(s["n_seeds_alpha"]),
            n_seeds_beta=int(s["n_seeds_beta"]),
            hydrophobicity=float(s["hydrophobicity"]),
        )
        for s in entry.get("sites", [])
    ]
    return SurfaceBindFeatures(
        has_data=True,
        n_sites=int(entry.get("n_sites", 0)),
        n_seeds_alpha=int(entry.get("n_seeds_alpha", 0)),
        n_seeds_beta=int(entry.get("n_seeds_beta", 0)),
        n_seeds_total=int(entry.get("n_seeds_total", 0)),
        chain=entry.get("chain"),
        sites=sites,
        main_class=entry.get("main_class"),
        sub_class=entry.get("sub_class"),
        protein_name=entry.get("protein_name"),
        pdbs=list(entry.get("pdbs", [])),
    )


def lookup(uniprot_acc: str) -> SurfaceBindFeatures:
    """Return the SURFACE-Bind summary block for ``uniprot_acc``.

    Tries public D1 first (``surface_bind_protein`` + ``surface_bind_site``).
    Falls back to the checked-in summary JSON when D1 isn't reachable —
    no CLOUDFLARE_* env vars in the worktree, the table is missing, or a
    transient network blip.

    Returns a default :class:`SurfaceBindFeatures` (``has_data=False``)
    when the accession isn't in either source — the explicit "not in
    SURFACE-Bind" signal that distinguishes "absent from SURFACE-Bind"
    from "present but un-scored" (the latter is ``has_data=True`` with
    an empty ``sites`` list).

    ``has_data`` is set to ``True`` whenever the protein appears in
    SURFACE-Bind's authoritative ``results_no_TM.csv`` even when the
    per-site array is empty (the protein got scored but no patches
    cleared the targetability threshold — a real "no good binder
    sites" signal). Use ``len(sites) > 0`` to distinguish "scored
    with sites" from "scored without sites".
    """
    d1_hit = _lookup_d1(uniprot_acc)
    if d1_hit is not None:
        return d1_hit
    return _lookup_json(uniprot_acc)
